World builder pc-> development
HU-ICT-LAB/WebVR-Demo pull request #355
Opened 2022-01-31 13:26 UTC by FlorisVideler

2022-01-31 13:31 UTC, DaanWesterhof commented on tardis-world/index.html
> +        <script src="../scripts/browserMqtt.js" type="text/javascript"></script>
These are already included, wont this cause issues?

2022-01-31 13:33 UTC, DaanWesterhof requested changes
I dont think the commit at the tardis world index is needed. Code in main.js looks great, but the file is VERY large and i think it can be split into atleast 2 or 3 files, so the code will be easier to digest for other developers and its clearer what code does what.

2022-01-31 13:35 UTC, FlorisVideler commented
Will do

2022-02-03 14:30 UTC, DaanWesterhof requested changes
looks good, still need to remove the addition in the tardis-world/index.html of src="../scripts/browserMqtt.js" and src="../scripts/mqtt_client.js"
otherwise perfect

2022-02-03 15:41 UTC, merged